name: Generate Pacman SVG

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: qianyu15
          outputs: pacman.svg?palette=github-dark

      - name: Commit and push
        run: |
          git config user.name "qianyu15"
          git config user.email "qianyuyangvip@gmail.com"
          git add pacman.svg
          git commit -m "update pacman" || echo "no changes"
          git push origin main
