name: Generate Pacman

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: qianyu15
          outputs: pacman.svg

      - name: Push output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: /
